# Generated by Django 4.1.7 on 2023-04-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
